### ISSUE TITLE
Menu Option - Disabling non-spam signatures

### ISSUE THREAD

**Issue by TheGr8Wonder** [E-F-A/v3#398] opened 2017-10-09 20:42 UTC
Currently when going to 9 -> 1 -> N -> Y, upon a second run through the same menu, it will still prompt to "Disable" signatures, even though they are already disabled

**Comment by shawniverson** [comment] 2017-12-31 21:19
Working as intended, despite this.  Will be addressed in v4.

**Closed by shawniverson** 2017-12-31 21:19 UTC
Labels: bug, wontfix
